### ISSUE TITLE
problem z Rails 3

### ISSUE THREAD

**Issue by schiza** [grk/polish#4]
przy walidacjach w Rails 3, widać stary styl (z Rails 2) w tłumaczeniach:

```
nie może być puste, jest za krótkie (minimalnie {{count}} znaki)
```

W związku z tym, chciałem użyć branch'a rails3.
Wpis w Gemfile:

```
gem 'polish', :git => 'git://github.com/grk/polish.git', :branch => 'rails3'
```

Przy bundle install dostaję taki oto warning:

```
Using polish (0.0.4) from git://github.com/grk/polish.git (at rails3) 
polish at /home/schiza/.bundler/ruby/1.9.1/polish-cfab4d5c11b8 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
["init.rb", "lib/polish/backend", "lib/polish/backend/advanced.rb", "lib/vendor", "lib/vendor/i18n", "lib/vendor/i18n/CHANGELOG.textile", "lib/vendor/i18n/i18n.gemspec", "lib/vendor/i18n/lib", "lib/vendor/i18n/lib/i18n", "lib/vendor/i18n/lib/i18n/backend", "lib/vendor/i18n/lib/i18n/backend/base.rb", "lib/vendor/i18n/lib/i18n/backend/cache.rb", "lib/vendor/i18n/lib/i18n/backend/chain.rb", "lib/vendor/i18n/lib/i18n/backend/fallbacks.rb", "lib/vendor/i18n/lib/i18n/backend/gettext.rb", "lib/vendor/i18n/lib/i18n/backend/pluralization.rb", "lib/vendor/i18n/lib/i18n/backend/simple.rb", "lib/vendor/i18n/lib/i18n/exceptions.rb", "lib/vendor/i18n/lib/i18n/gettext.rb", "lib/vendor/i18n/lib/i18n/helpers", "lib/vendor/i18n/lib/i18n/helpers/gettext.rb", "lib/vendor/i18n/lib/i18n/locale", "lib/vendor/i18n/lib/i18n/locale/fallbacks.rb", "lib/vendor/i18n/lib/i18n/locale/tag", "lib/vendor/i18n/lib/i18n/locale/tag/parents.rb", "lib/vendor/i18n/lib/i18n/locale/tag/rfc4646.rb", "lib/vendor/i18n/lib/i18n/locale/tag/simple.rb", "lib/vendor/i18n/lib/i18n/locale/tag.rb", "lib/vendor/i18n/lib/i18n/string.rb", "lib/vendor/i18n/lib/i18n.rb", "lib/vendor/i18n/MIT-LICENSE", "lib/vendor/i18n/Rakefile", "lib/vendor/i18n/README.textile", "lib/vendor/i18n/test", "lib/vendor/i18n/test/all.rb", "lib/vendor/i18n/test/api", "lib/vendor/i18n/test/api/basics.rb", "lib/vendor/i18n/test/api/interpolation.rb", "lib/vendor/i18n/test/api/lambda.rb", "lib/vendor/i18n/test/api/link.rb", "lib/vendor/i18n/test/api/localization", "lib/vendor/i18n/test/api/localization/date.rb", "lib/vendor/i18n/test/api/localization/date_time.rb", "lib/vendor/i18n/test/api/localization/lambda.rb", "lib/vendor/i18n/test/api/localization/time.rb", "lib/vendor/i18n/test/api/pluralization.rb", "lib/vendor/i18n/test/api/translation.rb", "lib/vendor/i18n/test/backend", "lib/vendor/i18n/test/backend/cache", "lib/vendor/i18n/test/backend/cache/cache_test.rb", "lib/vendor/i18n/test/backend/chain", "lib/vendor/i18n/test/backend/chain/api_test.rb", "lib/vendor/i18n/test/backend/chain/chain_test.rb", "lib/vendor/i18n/test/backend/fallbacks", "lib/vendor/i18n/test/backend/fallbacks/api_test.rb", "lib/vendor/i18n/test/backend/fallbacks/fallbacks_test.rb", "lib/vendor/i18n/test/backend/pluralization", "lib/vendor/i18n/test/backend/pluralization/api_test.rb", "lib/vendor/i18n/test/backend/pluralization/pluralization_test.rb", "lib/vendor/i18n/test/backend/simple", "lib/vendor/i18n/test/backend/simple/all.rb", "lib/vendor/i18n/test/backend/simple/api_test.rb", "lib/vendor/i18n/test/backend/simple/lookup_test.rb", "lib/vendor/i18n/test/backend/simple/setup.rb", "lib/vendor/i18n/test/backend/simple/translations_test.rb", "lib/vendor/i18n/test/fixtures", "lib/vendor/i18n/test/fixtures/locales", "lib/vendor/i18n/test/fixtures/locales/de.po", "lib/vendor/i18n/test/fixtures/locales/en.rb", "lib/vendor/i18n/test/fixtures/locales/en.yml", "lib/vendor/i18n/test/fixtures/locales/plurals.rb", "lib/vendor/i18n/test/gettext", "lib/vendor/i18n/test/gettext/api_test.rb", "lib/vendor/i18n/test/gettext/backend_test.rb", "lib/vendor/i18n/test/i18n_exceptions_test.rb", "lib/vendor/i18n/test/i18n_load_path_test.rb", "lib/vendor/i18n/test/i18n_test.rb", "lib/vendor/i18n/test/locale", "lib/vendor/i18n/test/locale/fallbacks_test.rb", "lib/vendor/i18n/test/locale/tag", "lib/vendor/i18n/test/locale/tag/rfc4646_test.rb", "lib/vendor/i18n/test/locale/tag/simple_test.rb", "lib/vendor/i18n/test/string_test.rb", "lib/vendor/i18n/test/test_helper.rb", "lib/vendor/i18n/test/with_options.rb", "lib/vendor/i18n/vendor", "lib/vendor/i18n/vendor/po_parser.rb", "lib/vendor/i18n/VERSION"] are not files
```

A przy próbie uruchomienia serwera:

```
$ rails s

    /var/lib/gems/1.9.1/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require': no such file to load -- action_view_ext/helpers/date_helper (LoadError)
    from /var/lib/gems/1.9.1/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `block in require'
    from /var/lib/gems/1.9.1/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /var/lib/gems/1.9.1/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /var/lib/gems/1.9.1/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.9.1/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
    from /home/schiza/.bundler/ruby/1.9.1/polish-cfab4d5c11b8/lib/polish.rb:9:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:68:in `require'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:66:in `each'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:66:in `block in require'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:55:in `each'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler/runtime.rb:55:in `require'
    from /var/lib/gems/1.9.1/gems/bundler-1.0.12/lib/bundler.rb:120:in `require'
    from /home/schiza/ruby/praca/sonik/config/application.rb:7:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/railties-3.0.9/lib/rails/commands.rb:28:in `require'
    from /var/lib/gems/1.9.1/gems/railties-3.0.9/lib/rails/commands.rb:28:in `block in <top (required)>'
    from /var/lib/gems/1.9.1/gems/railties-3.0.9/lib/rails/commands.rb:27:in `tap'
    from /var/lib/gems/1.9.1/gems/railties-3.0.9/lib/rails/commands.rb:27:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Czy da się jakoś poprawnie użyć tego brancha? Czy po prostu jest w tej chwili jakiś bug? I jak naprawić ten problem z `{{count}}` ?

**Comment by grk** [comment]
Branch rails3 to stary feature branch, używałem go jak rails3 było nowe, jest już zmergowany do master.

Wrzuciłem zmiany do master, sprawdź, czy o to chodziło. Jak tak to popchnę nową wersję gema.

A w ogóle to nie wiem czy te tłumaczenia są potrzebne, w rails-i18n też są.

**Comment by schiza** [comment]
już działa :) wielkie dzięki!
prosiłbym o comment jak będzie pchnięty gem

**Comment by grk** [comment]
https://rubygems.org/gems/polish/versions/0.1.2
